# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A111F)
$foreground = rgb(E2E2F6)
$color0 = rgb(2E2534)
$color1 = rgb(715692)
$color2 = rgb(756198)
$color3 = rgb(796B9E)
$color4 = rgb(7D76A5)
$color5 = rgb(8181AB)
$color6 = rgb(8181AB)
$color7 = rgb(CDCDE9)
$color8 = rgb(908FA3)
$color9 = rgb(9673C2)
$color10 = rgb(9C81CB)
$color11 = rgb(A18FD3)
$color12 = rgb(A79DDC)
$color13 = rgb(ACABE4)
$color14 = rgb(ACABE4)
$color15 = rgb(CDCDE9)
