exec-once = $UserScripts/RainbowBorders.sh &
exec-once = ags &
exec-once = hypridle &
exec-once = kdeconnectd &
exec-once = nm-applet --indicator &
exec-once = pypr &
exec-once = rog-control-center &
exec-once = swaync &
exec-once = waybar &
